Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -11,32 +11,33 @@ variables:
 image: rohimuhamadd/alpine-ci-cd:latest
 
 .default_before_script: &default_before_script
-  before_script:
-    - ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
-    - eval $(ssh-agent -s)
-    - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
-    - chmod 600 /tmp/deploy_key
-    - ssh-add /tmp/deploy_key
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - ssh-keyscan -H ${DEPLOY_SERVER_STAGING_SANTOSA} >> ~/.ssh/known_hosts
-    - mkdir -p /tmp/scripts
-    - |
-      scp -o StrictHostKeyChecking=no "$SSH_USER_STAGING_SANTOSA"@"${DEPLOY_SERVER_STAGING_SANTOSA}":/home/sanbe-odoo/script/send_notification.sh /tmp/scripts/
-      if [ -f "/tmp/scripts/send_notification.sh" ]; then
-        echo "✅ File successfully copied."
-        dos2unix /tmp/scripts/send_notification.sh
-        tr -d '\r' < /tmp/scripts/send_notification.sh > /tmp/scripts/send_notification_fixed.sh
-        mv /tmp/scripts/send_notification_fixed.sh /tmp/scripts/send_notification.sh
-        chmod +x /tmp/scripts/send_notification.sh
-      else
-        echo "❌ Error: /tmp/scripts/send_notification.sh not found!"
-        exit 1
-      fi
-
-
-.default_staging_rule: &default_staging_rule
-  - if: '$CI_COMMIT_BRANCH == $BRANCH_STAGING_SANTOSA'
+#  before_script:
+#    - ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
+#    - eval $(ssh-agent -s)
+#    - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
+#    - chmod 600 /tmp/deploy_key
+#    - ssh-add /tmp/deploy_key
+#    - mkdir -p ~/.ssh
+#    - chmod 700 ~/.ssh
+#    - ssh-keyscan -H ${DEPLOY_SERVER_STAGING_SANTOSA} >> ~/.ssh/known_hosts
+#    - ssh-keyscan -H ${DEPLOY_SERVER_PROD} >> ~/.ssh/known_hosts
+#    - mkdir -p /tmp/scripts
+#    - |
+#      scp -o StrictHostKeyChecking=no "${SSH_USER_STAGING_SANTOSA:-SSH_USER_PROD}"@"${DEPLOY_SERVER_STAGING_SANTOSA:-DEPLOY_SERVER_PROD}":/home/albert/script/send_notification.sh /tmp/scripts/
+#      if [ -f "/tmp/scripts/send_notification.sh" ]; then
+#        echo "✅ File successfully copied."
+#        dos2unix /tmp/scripts/send_notification.sh
+#        tr -d '\r' < /tmp/scripts/send_notification.sh > /tmp/scripts/send_notification_fixed.sh
+#        mv /tmp/scripts/send_notification_fixed.sh /tmp/scripts/send_notification.sh
+#        chmod +x /tmp/scripts/send_notification.sh
+#      else
+#        echo "❌ Error: /tmp/scripts/send_notification.sh not found!"
+#        exit 1
+#      fi
+#
+#
+#.default_staging_rule: &default_staging_rule
+#  - if: '$CI_COMMIT_BRANCH == $BRANCH_STAGING_SANTOSA'
 
 # PRE-MERGE
 #check_base_branch:
